### ISSUE TITLE
Core dump on using the new 2.3 version.

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#114]
I find that the new version on running, gets coredumped. I have added multiple traces because I am unable to figure out where the dump is happening.

My procedure for updating to this release was to compile ktistec statically, and copy the `server` and `etc` directory over. Please let me know if I am missing any directories or files.

```
cd /home/rahul/ktistec/rootdir/app; LOG_LEVEL=INFO ./server
SQLite3 version 3.42.0
add-index-to-relationships: applied in 24.1916s
2024-09-27T01:13:36.027773Z NOTICE - database: Slow query [  1582.632ms] -- DELETE FROM tasks WHERE (complete = 1 OR backtrace IS NOT NULL) AND created_at < date('now', '-1 month') -- args: nil
2024-09-27T01:13:36.027921Z NOTICE - database: [{0, "SCAN tasks"}]
[development] Ktistec is ready to lead at http://0.0.0.0:3000
2024-09-27T01:13:36.480093Z NOTICE - database: Slow query [   435.238ms] -- DELETE FROM sessions WHERE account_id IS NULL AND updated_at < ? -- args: [2024-09-26 01:13:36.044799915 +00:00]
2024-09-27T01:13:36.480194Z NOTICE - database: [{0, "SEARCH sessions USING INDEX idx_sessions_account_id (account_id=?)"}]
2024-09-27 01:13:41 UTC 200 GET /.well-known/nodeinfo 50.78ms
2024-09-27 01:17:05 UTC 200 GET /.well-known/nodeinfo/2.1 203282.5ms
2024-09-27T01:17:05.067550Z NOTICE - database: Slow query [203257.084ms] -- SELECT COUNT(o.id) FROM accounts AS c JOIN relationships AS r ON likelihood(r.from_iri = c.iri, 0.99) AND r.type = "Relationship::Content::Outbox" JOIN activities AS a ON a.iri = r.to_iri AND a.type IN ("ActivityPub::Activity::Announce", "ActivityPub::Activity::Create") JOIN objects AS o ON o.iri = a.object_iri JOIN actors AS t ON t.iri = o.attributed_to_iri WHERE o.visible = 1 AND likelihood(o.in_reply_to_iri IS NULL, 0.25) AND o.deleted_at IS NULL AND o.blocked_at IS NULL AND t.deleted_at IS NULL AND t.blocked_at IS NULL AND a.undone_at IS NULL -- args: nil
2024-09-27T01:17:05.070790Z NOTICE - database: [{0, "SCAN c USING COVERING INDEX idx_accounts_iri"}, {0, "BLOOM FILTER ON o (visible=?)"}, {0, "SEARCH o USING AUTOMATIC PARTIAL COVERING INDEX (visible=?)"}, {0, "SEARCH t USING INDEX idx_actors_iri (iri=?)"}, {0, "SEARCH a USING INDEX idx_activities_object_iri (object_iri=?)"}, {0, "SEARCH r USING INDEX idx_relationships_to_iri (to_iri=?)"}]
Floating point exception (core dumped)
```

```
cd /home/rahul/ktistec/rootdir/app; LOG_LEVEL=INFO ./server
SQLite3 version 3.42.0
2024-09-27T01:23:34.447942Z NOTICE - database: Slow query [   902.835ms] -- DELETE FROM tasks WHERE (complete = 1 OR backtrace IS NOT NULL) AND created_at < date('now', '-1 month') -- args: nil
2024-09-27T01:23:34.448123Z NOTICE - database: [{0, "SCAN tasks"}]
[development] Ktistec is ready to lead at http://0.0.0.0:3000
2024-09-27T01:23:34.549639Z NOTICE - database: Slow query [    95.613ms] -- DELETE FROM sessions WHERE account_id IS NULL AND updated_at < ? -- args: [2024-09-26 01:23:34.453969026 +00:00]
2024-09-27T01:23:34.549740Z NOTICE - database: [{0, "SEARCH sessions USING INDEX idx_sessions_account_id (account_id=?)"}]
2024-09-27 01:23:43 UTC 409 POST /actors/rahul/inbox 50.15ms
2024-09-27 01:23:46 UTC 409 POST /actors/rahul/inbox 13.21ms
2024-09-27 01:23:47 UTC 409 POST /actors/rahul/inbox 8.71ms
2024-09-27 01:23:48 UTC 409 POST /actors/rahul/inbox 8.14ms
2024-09-27 01:23:50 UTC 409 POST /actors/rahul/inbox 8.89ms
2024-09-27 01:23:50 UTC 409 POST /actors/rahul/inbox 8.21ms
2024-09-27 01:23:51 UTC 409 POST /actors/rahul/inbox 8.66ms
2024-09-27 01:23:53 UTC 409 POST /actors/rahul/inbox 8.54ms
2024-09-27 01:23:54 UTC 409 POST /actors/rahul/inbox 8.48ms
2024-09-27 01:23:54 UTC 409 POST /actors/rahul/inbox 8.19ms
2024-09-27 01:23:55 UTC 409 POST /actors/rahul/inbox 9.79ms
2024-09-27 01:24:01 UTC 409 POST /actors/rahul/inbox 7.93ms
2024-09-27 01:24:02 UTC 409 POST /actors/rahul/inbox 9.68ms
2024-09-27 01:24:03 UTC 409 POST /actors/rahul/inbox 7.96ms
2024-09-27 01:24:22 UTC 200 GET /actors/rahul 584.18ms
2024-09-27T01:24:22.042681Z NOTICE - database: Slow query [   373.513ms] -- SELECT "a"."type","a"."id","a"."created_at","a"."updated_at","a"."type","a"."undone_at","a"."iri","a"."visible","a"."published","a"."actor_iri","a"."object_iri","a"."target_iri","a"."to","a"."cc","a"."summary" FROM activities AS a JOIN actors AS act ON act.iri = a.actor_iri JOIN objects AS obj ON obj.iri = a.object_iri WHERE a.actor_iri = ? AND a.object_iri = ? AND a.type = "ActivityPub::Activity::Announce"   AND "act".deleted_at IS NULL AND "act".blocked_at IS NULL   AND "obj".deleted_at IS NULL AND "obj".blocked_at IS NULL   AND "a".undone_at IS NULL  -- args: ["https://gopinath.org/actors/rahul", "https://social.wildeboer.net/users/jwildeboer/statuses/113206140750411257"]
2024-09-27T01:24:22.042938Z NOTICE - database: [{0, "SEARCH act USING INDEX idx_actors_iri (iri=?)"}, {0, "SEARCH obj USING INDEX idx_objects_iri (iri=?)"}, {0, "SEARCH a USING INDEX idx_activities_actor_iri (actor_iri=?)"}]
Floating point exception (core dumped)
```

```
cd /home/rahul/ktistec/rootdir/app; LOG_LEVEL=INFO ./server
SQLite3 version 3.42.0
[development] Ktistec is ready to lead at http://0.0.0.0:3000
2024-09-27 01:28:06 UTC 409 POST /actors/rahul/inbox 46.45ms
2024-09-27 01:28:21 UTC 409 POST /actors/rahul/inbox 8.75ms
2024-09-27 01:28:22 UTC 409 POST /actors/rahul/inbox 7.93ms
2024-09-27 01:28:23 UTC 200 GET /actors/rahul 119.59ms
2024-09-27T01:28:23.690814Z NOTICE - database: Slow query [    52.711ms] -- SELECT "o"."type","o"."id","o"."blocked_at","o"."created_at","o"."updated_at","o"."deleted_at","o"."type","o"."iri","o"."visible","o"."published","o"."attributed_to_iri","o"."in_reply_to_iri","o"."replies_iri","o"."thread","o"."to","o"."cc","o"."name","o"."summary","o"."content","o"."media_type","o"."source","o"."attachments","o"."urls" FROM objects AS o JOIN actors AS t ON t.iri = o.attributed_to_iri JOIN activities AS a ON a.object_iri = o.iri AND a.type IN ("ActivityPub::Activity::Announce", "ActivityPub::Activity::Create") JOIN relationships AS r ON r.to_iri = a.iri AND r.type = "Relationship::Content::Outbox" WHERE r.from_iri = ? AND o.visible = 1 AND likelihood(o.in_reply_to_iri IS NULL, 0.25)  AND "o".deleted_at IS NULL AND "o".blocked_at IS NULL   AND "t".deleted_at IS NULL AND "t".blocked_at IS NULL   AND "a".undone_at IS NULL  ORDER BY r.id DESC LIMIT ? OFFSET ? -- args: ["https://gopinath.org/actors/rahul", 11, 0]
2024-09-27T01:28:23.691144Z NOTICE - database: [{0, "SEARCH r USING INDEX idx_relationships_type (type=?)"}, {0, "SEARCH a USING INDEX idx_activities_iri (iri=?)"}, {0, "SEARCH o USING INDEX idx_objects_iri (iri=?)"}, {0, "SEARCH t USING INDEX idx_actors_iri (iri=?)"}]
2024-09-27 01:28:24 UTC 200 GET /3rd/semantic-2.4.1.min.css 72.63ms
2024-09-27 01:28:24 UTC 200 GET /dist/site.bundle.js 29.45ms
2024-09-27 01:28:24 UTC 200 GET /uploads/28524ef7/a3b5/4035/1.jpg 934.8µs
2024-09-27 01:28:27 UTC 200 GET /uploads/2a52c201/ea9e/4eb4/1.jpg 3.64ms
2024-09-27 01:28:27 UTC 200 GET /3rd/themes/default/assets/fonts/Lato-Bold.woff2 2.04ms
2024-09-27 01:28:27 UTC 200 GET /3rd/themes/default/assets/fonts/Lato-Italic.woff2 2.0ms
2024-09-27 01:28:27 UTC 200 GET /3rd/themes/default/assets/fonts/icons.woff2 2.63ms
2024-09-27 01:28:27 UTC 200 GET /3rd/themes/default/assets/fonts/Lato-Regular.woff2 2.38ms
2024-09-27 01:28:29 UTC 200 GET /uploads/c4fcf89d/3b0b/4913/1.jpg 1.99ms
2024-09-27 01:28:52 UTC 200 POST /actors/rahul/inbox 86.57ms
Floating point exception (core dumped)
```

```
cd /home/rahul/ktistec/rootdir/app; LOG_LEVEL=DEBUG ./server
SQLite3 version 3.42.0
2024-09-27T01:30:10.214367Z  DEBUG - database: Query [    15.637ms] -- DELETE FROM tasks WHERE (complete = 1 OR backtrace IS NOT NULL) AND created_at < date('now', '-1 month') -- args: nil
2024-09-27T01:30:10.214606Z  DEBUG - database: Query [     0.214ms] -- UPDATE tasks SET running = 0 WHERE running = 1 -- args: nil
2024-09-27T01:30:10.214841Z  DEBUG - database: Query [     0.143ms] -- SELECT "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" FROM "tasks" WHERE "type" IN ("Task::Backup") AND running = 0 AND complete = 0 AND backtrace IS NULL -- args: nil
2024-09-27T01:30:10.221058Z  DEBUG - database: Query [     6.035ms] -- INSERT OR REPLACE INTO tasks ("id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at") VALUES (?,?,?,?,?,?,?,?,?,?,?) -- args: [nil, 2024-09-27 01:30:10.214969765 UTC, 2024-09-27 01:30:10.214965197 UTC, "Task::Backup", "", "", false, false, nil, nil, nil]
[development] Ktistec is ready to lead at http://0.0.0.0:3000
2024-09-27T01:30:10.222217Z  DEBUG - database: Query [     0.213ms] -- SELECT "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" FROM "tasks" WHERE "type" IN ("Task::Performance") AND running = 0 AND complete = 0 AND backtrace IS NULL -- args: nil
2024-09-27T01:30:10.222441Z  DEBUG - database: Query [     0.166ms] -- SELECT "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","state","failures","state" FROM "tasks" WHERE "type" IN ("Task::UpdateMetrics") AND running = 0 AND complete = 0 AND backtrace IS NULL -- args: nil
2024-09-27T01:30:10.222614Z  DEBUG - database: Query [     0.130ms] -- SELECT "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" FROM "tasks" WHERE "type" IN ("Task::Monitor") AND running = 0 AND complete = 0 AND backtrace IS NULL -- args: nil
2024-09-27T01:30:10.231326Z  DEBUG - database: Query [     8.624ms] -- DELETE FROM sessions WHERE account_id IS NULL AND updated_at < ? -- args: [2024-09-26 01:30:10.222653535 +00:00]
2024-09-27T01:30:10.236220Z  DEBUG - database: Query [     4.655ms] -- INSERT OR REPLACE INTO points ("id","chart","timestamp","value") VALUES (?,?,?,?) -- args: [nil, "server-start", 2024-09-27 01:30:10.231330418 UTC, 1]
2024-09-27T01:30:10.251263Z  DEBUG - database: Query [     5.536ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:10.245634992 UTC]
2024-09-27T01:30:10.251516Z  DEBUG - database: Query [     0.170ms] -- SELECT "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" FROM "tasks" WHERE "id" = ? -- args: [833117]
2024-09-27T01:30:10.289657Z  DEBUG - database: Query [    38.055ms] -- INSERT OR REPLACE INTO tasks ("id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at") VALUES (?,?,?,?,?,?,?,?,?,?,?) -- args: [833117, 2024-09-27 01:30:10.214000000 UTC, 2024-09-27 01:30:10.251533863 UTC, "Task::Backup", "", "", false, true, nil, nil, 2024-09-27 01:30:10.251281497 UTC]
2024-09-27T01:30:10.289825Z  DEBUG - database: Query [     0.113ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:10.289668695 UTC]
2024-09-27T01:30:15.290198Z  DEBUG - database: Query [     0.124ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:15.290002401 UTC]
2024-09-27T01:30:20.290726Z  DEBUG - database: Query [     0.127ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:20.290519210 UTC]
2024-09-27T01:30:25.291102Z  DEBUG - database: Query [     0.205ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:25.290783880 UTC]
2024-09-27T01:30:30.290692Z  DEBUG - database: Query [     0.132ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:30:30.290455213 UTC]
Floating point exception (core dumped)
```

```
2024-09-27T01:31:22.497188Z  DEBUG - database: Query [     0.056ms] -- UPDATE actors SET down_at = ? WHERE id = ? -- args: [nil, 48013]
2024-09-27T01:31:22.497408Z  DEBUG - database: Query [     0.160ms] -- SELECT "type","id","blocked_at","created_at","updated_at","deleted_at","type","iri","username","pem_public_key","pem_private_key","inbox","outbox","following","followers","name","summary","icon","image","urls","attachments","down_at" FROM "actors" WHERE "iri" = ? AND "deleted_at" IS NULL AND "type" IN ("ActivityPub::Actor::Application","ActivityPub::Actor::Group","ActivityPub::Actor::Organization","ActivityPub::Actor::Person","ActivityPub::Actor::Service","ActivityPub::Actor") -- args: ["https://gopinath.org/actors/rahul"]
2024-09-27T01:31:22.497578Z  DEBUG - database: Query [     0.121ms] -- SELECT "type","id","blocked_at","created_at","updated_at","deleted_at","type","iri","visible","published","attributed_to_iri","in_reply_to_iri","replies_iri","thread","to","cc","name","summary","content","media_type","source","attachments","urls" FROM "objects" WHERE "iri" = ? AND "deleted_at" IS NULL -- args: ["https://bgme.me/users/smilemonkey"]
2024-09-27T01:31:22.497850Z  DEBUG - database: Query [     0.145ms] -- SELECT "type","id","blocked_at","created_at","updated_at","deleted_at","type","iri","username","pem_public_key","pem_private_key","inbox","outbox","following","followers","name","summary","icon","image","urls","attachments","down_at" FROM "actors" WHERE "iri" = ? AND "deleted_at" IS NULL AND "type" IN ("ActivityPub::Actor::Application","ActivityPub::Actor::Group","ActivityPub::Actor::Organization","ActivityPub::Actor::Person","ActivityPub::Actor::Service","ActivityPub::Actor") -- args: ["https://bgme.me/users/smilemonkey"]
2024-09-27T01:31:22.498093Z  DEBUG - database: Query [     0.136ms] -- SELECT "type","id","created_at","updated_at","type","undone_at","iri","visible","published","actor_iri","object_iri","target_iri","to","cc","summary" FROM "activities" WHERE "iri" = ? AND "undone_at" IS NULL -- args: ["https://bgme.me/users/smilemonkey#delete"]
2024-09-27T01:31:25.512064Z  DEBUG - database: Query [     0.167ms] -- UPDATE tasks SET running = 1 WHERE running = 0 AND complete = 0 AND backtrace IS NULL AND (next_attempt_at IS NULL OR next_attempt_at < ?) RETURNING "type","id","created_at","updated_at","type","source_iri","subject_iri","running","complete","backtrace","next_attempt_at","last_attempt_at","failures","state" -- args: [2024-09-27 01:31:25.511824717 UTC]
Floating point exception (core dumped)
```

**Comment by toddsundsted** [comment]
what version of ktistec are you compiling? keeping everything else the same, can you compile an earlier version that runs successfully?

**Comment by vrthra** [comment]
I tried the 2.3 version latest check out from your main branch. I went back to the previous version (and restored my db), and it runs.

**Comment by toddsundsted** [comment]
there's nothing that i can think of that i added recently that would lead to a floating point exception. the server doesn't make extensive use of floating point in the first place, and i'm pretty sure that the crystal runtime catches the obvious problems (rather than just crashes).

**Comment by vrthra** [comment]
I am very much memory constrained, so it may be an issue.

I attached `gdb` to the process, and this is the trace I am getting
```
(gdb) bt
#0  0x00007ffff4175bb9 in __nptl_tls_static_size_for_stack () at ../nptl/nptl-stack.h:58
#1  __pthread_early_init () at ../sysdeps/nptl/pthread_early_init.h:46
#2  __libc_early_init (initial=<optimized out>) at ./elf/libc_early_init.c:44
#3  0x000000000217ac1c in dl_open_worker_begin ()
#4  0x0000000002180e64 in _dl_catch_exception ()
#5  0x000000000217a3d0 in dl_open_worker ()
#6  0x0000000002180e64 in _dl_catch_exception ()
#7  0x000000000217a5f7 in _dl_open ()
#8  0x00000000021810c6 in do_dlopen ()
#9  0x0000000002180e64 in _dl_catch_exception ()
#10 0x0000000002180f23 in _dl_catch_error ()
#11 0x0000000002181107 in dlerror_run ()
#12 0x0000000002181589 in __libc_dlopen_mode ()
#13 0x000000000216ea31 in __nss_lookup_function ()
#14 0x000000000215fb17 in gaih_inet.constprop ()
#15 0x0000000002160e8b in getaddrinfo ()
#16 0x0000000001a06b95 in initialize () at /data/crystal-1.10.1-1/share/crystal/src/socket/addrinfo.cr:132
#17 0x0000000001a06820 in initialize () at /data/crystal-1.10.1-1/share/crystal/src/socket/tcp_socket.cr:29
#18 0x0000000001a0676c in new () at /data/crystal-1.10.1-1/share/crystal/src/socket/tcp_socket.cr:29
#19 0x0000000001a021af in io () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:797
#20 0x0000000001a01afc in send_request () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:678
#21 0x0000000001a01a99 in exec_internal_single () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:609
#22 0x0000000001a017b0 in exec_internal () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:592
#23 0x0000000001a01487 in exec () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:585
#24 0x0000000001a013f6 in exec () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:721
#25 0x0000000001a013a6 in get () at /data/crystal-1.10.1-1/share/crystal/src/http/client.cr:410
#26 0x0000000001a00316 in open () at /data/ktistec/src/framework/open.cr:29
#27 0x000000000184e1b6 in dereference? () at /data/ktistec/src/framework/open.cr:98
#28 0x00000000004611f1 in -> () at /data/ktistec/src/controllers/inboxes.cr:88
#29 0x00000000004584d4 in -> () at /data/ktistec/lib/kemal/src/kemal/route.cr:12
#30 0x0000000000963e23 in process_request () at /data/ktistec/lib/kemal/src/kemal/route_handler.cr:52
#31 0x0000000000963d56 in call () at /data/ktistec/lib/kemal/src/kemal/route_handler.cr:17
#32 0x000000000096a454 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#33 0x0000000000969e7b in call () at /data/ktistec/lib/kemal/src/kemal/websocket_handler.cr:13
#34 0x0000000001bb6d03 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#35 0x0000000001bb6516 in call () at /data/ktistec/src/handlers/canonical.cr:15
#36 0x0000000000a0b660 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#37 0x0000000000a0b348 in call () at /data/ktistec/src/framework/rewrite.cr:8
#38 0x0000000000a0b02f in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#39 0x0000000000a0abfe in call () at /data/ktistec/src/framework/method.cr:21
#40 0x0000000000a09ebe in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#41 0x0000000000a096f5 in call () at /data/ktistec/src/framework/csrf.cr:49
#42 0x0000000000a086dd in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#43 0x0000000000a07ab3 in call () at /data/ktistec/src/framework/auth.cr:13
#44 0x0000000001be378c in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#45 0x0000000001be2eb8 in call () at /data/ktistec/lib/kemal/src/kemal/static_file_handler.cr:11
#46 0x0000000001be248c in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#47 0x0000000001be21dd in call () at /data/ktistec/lib/kemal/src/kemal/exception_handler.cr:8
#48 0x0000000000962a42 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#49 0x0000000000962807 in call () at /data/ktistec/lib/kemal/src/kemal/head_request_handler.cr:57
#50 0x0000000001be1a55 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#51 0x0000000001be1396 in call () at /data/ktistec/lib/kemal/src/kemal/log_handler.cr:8
#52 0x0000000000963033 in call_next () at /data/crystal-1.10.1-1/share/crystal/src/http/server/handler.cr:30
#53 0x0000000000962e20 in call () at /data/ktistec/lib/kemal/src/kemal/init_handler.cr:15
#54 0x0000000001be695c in process () at /data/crystal-1.10.1-1/share/crystal/src/http/server/request_processor.cr:51
#55 0x0000000001be5941 in handle_client () at /data/crystal-1.10.1-1/share/crystal/src/http/server.cr:521
#56 0x00000000004fbf83 in -> () at /data/crystal-1.10.1-1/share/crystal/src/http/server.cr:451
#57 0x00000000007d5e4d in run () at /data/crystal-1.10.1-1/share/crystal/src/fiber.cr:146
#58 0x0000000000423566 in -> () at /data/crystal-1.10.1-1/share/crystal/src/fiber.cr:98
```

**Comment by vrthra** [comment]
Turns out it was an issue with library compatibility. Closing this as it is not an issue at Ktistec.

**Comment by vrthra** [comment]
By the way, something has changed for the better in 2.3 version. It feals **much** more responsive in my memory constrained environment.

**Comment by toddsundsted** [comment]
awesome! depending on what the previous version you were running was, it could be better. the memory footprint is still too big, but i was able to reduce build times, build memory, and runtime memory a bit. glad the issue is resolved in any case.
